### ISSUE TITLE
Getting duplicate records

### ISSUE THREAD

**Issue by xpdientUK** [fuzionnz/nz.co.fuzion.historicmembershipdata#1]
The extension returns duplicate records, sometimes 5 or more for the same contact.

It puts the count off.

**Comment by jitendrapurohit** [comment]
Hi @xpdientUK 

I've just pushed a [new commit](https://github.com/fuzionnz/nz.co.fuzion.historicmembershipdata/commit/4d2b079ff4f1138e4335745ad737f1b83501970d) to fix the duplicate rows in the search result.

Let us know if you still notice any issues.

Thanks.
